### ISSUE TITLE
tslab in VS Code

### ISSUE THREAD

**Issue by gregbacchus** [yunabe/tslab#65]
I'm just wondering if it's possible to use tslab with the VS Code Jupyter extension. I have installed tslab, but it doesn't show up in VS Code under the list of kernels.

Any ideas?

**Comment by gregbacchus** [comment]
Hmm. It eventually just showed up. Maybe it was after restarting VS Code.

**Comment by simonbengtsson** [comment]
Had the same issue and restarting vs code solved it for me as well.
