### ISSUE TITLE
Cannot import packages from nodejs.

### ISSUE THREAD

**Issue by LastsForever** [yunabe/tslab#69]
I hope to import packages from nodejs, thanks!

**Comment by vincenzon** [comment]
I find this works if you install the packages from a terminal you open in jupyter (I'm using jupyter-lab). So, start jupyter, open a shell, run: `npm install package-name`, then you can import from `package-name` in typescript notebooks.

**Comment by LastsForever** [comment]
> I find this works if you install the packages from a terminal you open in jupyter (I'm using jupyter-lab). So, start jupyter, open a terminal tab in jupyter, run: `npm install package-name`, then you can import from `package-name` in typescript notebooks.

Thanks! It seems only `npm install package-name` works. `npm link package-name` and `npm install -g package-name` won't.
