### ISSUE TITLE
TSLab version 1.0.21 not working properly with AllTheKernels kernel version 1.2.0

### ISSUE THREAD

**Issue by paolocarinci** [yunabe/tslab#98]
Whenever you execute a command in [AllTheKernels kernel](https://github.com/minrk/allthekernels) (either in a notebook or in a shell), e.g.

```
>jslab
console.log("Test");
```

the cell remains running indefinitley and no output is shown.
In the logs I spotted an error message that says that a JSONParseException has occurred.

```
[AllTheKernelsApp] Relaying execute_request to jslab
UnhandledPromiseRejection: SyntaxError: Unexpected token 'a', "a07332d4ce"... is not valid JSON
    at JSON.parse (<anonymous>)
    at ZmqMessage.fromRaw (/opt/jupyterhub/lib/node_modules/tslab/dist/jupyter.js:67:27)
    at ZmqServer.handleShellMessage (/opt/jupyterhub/lib/node_modules/tslab/dist/jupyter.js:315:32)
    at /opt/jupyterhub/lib/node_modules/tslab/dist/jupyter.js:435:30
```

while the AllTheKernels kernel works fine with all the other kernels I use (IPython, Gophernotes, Bash, C, IJava).

**Comment by paolocarinci** [comment]
Hello @yunabe, the solution provided by minrk seems to solve the problem: could you please consider accepting the merge request #99?
Thank you in advance

**Comment by yunabe** [comment]
Thank you for the erport @paolocarinci. I merged the pull request and pushed the new version.
